### ISSUE TITLE
Wind Burst, Swift Sneak, and Soul Speed displaced

### ISSUE THREAD

**Issue by Wazpiro** [jodeks-datapacks/Bigger-Stack-Size#6]
When I added the 1.3.2+ mod from modrinth to my pack it mixed Wind Burst, Swift Sneak, and Soul Speed to the loot table of all enchanted gear and books from structures. I don't know to how far it reaches but i found a leather pants in a shipwreck with Swift Sneak II, Wind Burst III was dropped from bartering and all the ways of guaranteed drop locations (Trial Chamber, Ancient City, and Piglin Bartering) don't guarantee said drops. It is ok in the latest version (1.21.3), and the un-modded/data packed version, and the modded version without the mod, it's just the mod that does it.

**Comment by Jodekq** [comment]
Weird, as this should not be possible
