### ISSUE TITLE
How do i remove the datapack

### ISSUE THREAD

**Issue by icedegreaser** [jodeks-datapacks/Bigger-Stack-Size#7]
Sorry if this sound STUPID but this datapack wont get removed from my world when i delete it, im trying to build a storage system and stackable minecart is ruining it

Thank you very much

**Comment by Jodekq** [comment]
I've uploaded a new version, with that installed do:
`/scoreboard player set &stack_mode config.biggerstacksize 3`
3 means that everything you drop on the ground will be reset, its not possible in a easier way. :(

**Comment by Jodekq** [comment]
you have to delete the file and then do `/reload`

**Comment by icedegreaser** [comment]
i did that, it didn't work, i will try again tho

**Comment by icedegreaser** [comment]
i dont really know why it didnt work the first try, but it worked now, im feeling so stupid, the mod is gone

Thank!!
